version: '3.8'

services:
  # Application service
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: task-management-app
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/task_management_dev?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=task_user
      - SPRING_DATASOURCE_PASSWORD=task_password
      - JWT_SECRET=development-jwt-secret-key-minimum-32-chars
    volumes:
      - app-logs:/app/logs
    networks:
      - task-management-network

  # MySQL database service
  mysql:
    image: mysql:8.0
    container_name: task-management-mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=task_management_dev
      - MYSQL_USER=task_user
      - MYSQL_PASSWORD=task_password
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - task-management-network
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  # Adminer for database management (optional)
  adminer:
    image: adminer
    container_name: task-management-adminer
    restart: unless-stopped
    ports:
      - "8082:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
    networks:
      - task-management-network

  # JFrog Artifactory OSS service
  artifactory:
    image: releases-docker.jfrog.io/jfrog/artifactory-oss:latest
    container_name: task-management-artifactory
    restart: always
    ports:
      - "8083:8081"  # Artifactory web UI and API
    environment:
      - EXTRA_JAVA_OPTIONS=-Xms512m -Xmx2g
      - ARTIFACTORY_USER=admin
      - ARTIFACTORY_PASSWORD=password
    volumes:
      - artifactory_data:/var/opt/jfrog/artifactory
      - ./artifactory/config/system.yaml:/opt/jfrog/artifactory/var/etc/system.yaml
    networks:
      - task-management-network

  artifactory-postgres:
    image: postgres:15
    container_name: artifactory-postgres
    restart: always
    environment:
      - POSTGRES_DB=artifactory
      - POSTGRES_USER=artifactory
      - POSTGRES_PASSWORD=artifactory
    volumes:
      - artifactory_postgres_data:/var/lib/postgresql/data
    networks:
      - task-management-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U artifactory"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mysql-data:
  app-logs:
  artifactory_data:
  artifactory_postgres_data:

networks:
  task-management-network:
    driver: bridge

