# Common Configuration for all profiles
spring:
  application:
    name: task-management-system
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
  # Disable Spring banner
  main:
    banner-mode: off

# Server configuration
server:
  port: 8080
  servlet:
    context-path: /api
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
  info:
    git:
      mode: full

# API Documentation with OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  packages-to-scan: com.example.taskmanagement.controller

# Logging configuration root
logging:
  level:
    root: INFO
    com.example.taskmanagement: INFO
    org.springframework: WARN
    org.hibernate: WARN

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-secret-key-should-be-at-least-32-chars-long}
  expiration: 86400000  # 24 hours in milliseconds
  issuer: task-management-system

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev
  # Database configuration
  datasource:
    url: jdbc:mysql://localhost:3306/task_management_dev?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
  # JPA/Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: none  # Disabled since we're using Flyway
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  # Flyway configuration
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: schema_history
    validate-on-migrate: true

# Logging configuration for dev
logging:
  level:
    com.example.taskmanagement: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Server port for dev
server:
  port: 8080

---
# Production Profile
spring:
  config:
    activate:
      on-profile: prod
  # Database configuration
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:task_management_prod}?useSSL=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 50
      minimum-idle: 10
  # JPA/Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  # Flyway configuration
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: schema_history
    validate-on-migrate: true

# Logging configuration for prod
logging:
  level:
    root: WARN
    com.example.taskmanagement: INFO
    org.springframework: ERROR
    org.hibernate: ERROR

# Server port for prod - can be overridden with environment variable
server:
  port: ${SERVER_PORT:8080}

# Enhanced security for production
server.ssl:
  enabled: ${SSL_ENABLED:false}
  key-store: ${SSL_KEYSTORE:classpath:keystore.p12}
  key-store-password: ${SSL_KEYSTORE_PASSWORD:password}
  key-store-type: PKCS12
  key-alias: ${SSL_KEY_ALIAS:tomcat}

# Disable developer tools in production
spring.devtools.add-properties: false

# Actuator security in production
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

